### ISSUE TITLE
Custom rule exception options required for automation

### ISSUE THREAD

**Issue by huornlmj** [controlplaneio/kubesec#124]
A rule exception option is required to facilitate the use of the kubesec tool in automation.  For example there might be a valid reason with a mitigating workaround for a container to run with elevated privileges, but kubesec would return a fail.  If it were possible to disable specific checks or use an override file or noqa option it would solve this limitation.

**Comment by 06kellyjac** [comment]
Currently `kubesec` is exclusively a security risk analysis tool for Kubernetes.
If you or your team have a specific policy around ignoring x rule for y deployment then I'd advise you pipe the output into `open-policy-agent`/`opa` to apply that policy.

If you want a flag for failing but still exit with error code `0` that'd be good addition.

**Comment by sublimino** [comment]
Agreed with Jack, Kubesec is willfully simple, hard-line, and opinionated :
] For granular policy application OPA/gatekeeper/conftest work better.

I know trivy allows return code customisation, an alternative is `kubesec
|| true` in the invocation string/pipeline for QA. If you know the rule's
score you're avoiding, that could also be added to the Kubesec score to
modify it, although it's clunky.

Do you think a dedicated flag for error codes would help your use case?

**Comment by 06kellyjac** [comment]
Since there's not been a response I'm going to close this. `opa` is a good option for this functionality for now.
If there is a strong desire for ignoring rules then we can look at re-opening but it does get pretty messy when people only want to ignore rules for certain blocks within a multi block yaml file etc
