### ISSUE TITLE
Kubernetes Admission Webhook documentation

### ISSUE THREAD

**Issue by bygui86** [controlplaneio/kubesec#218]
**Is your feature request related to a problem? Please describe.**
In the GitHub README it's mention that kubesec is available also as "Kubernetes Admission Webhook" but there's nothing in the documentation that describes how to use kubesec that way.

**Describe the solution you'd like**
I would be great to have a better documentation. Currently the doc is a bit confused, mention something and does not describe it in details (right for example kubesec as Kubernetes Admission Webhook")

**Comment by 06kellyjac** [comment]
The only mention of "Kubernetes Admission Controller" links you to the repo holding the code which contains details https://github.com/controlplaneio/kubesec-webhook

It does need quite a big overhaul though so I'll leave this as TODO until that's resolved

**Comment by bygui86** [comment]
I'm sorry @06kellyjac I read briefly and wrongly the link thinking of a self-link. Thanks for pointing it out!

Anyway yeah the documentation of kubesec-webhook is a bit tricky.

**Comment by 06kellyjac** [comment]
I'll actually close this in favor of https://github.com/controlplaneio/kubesec-webhook/issues/19
