### ISSUE TITLE
Ability to skip/ignore specific findings

### ISSUE THREAD

**Issue by kevinlewis31** [controlplaneio/kubesec#223]
Could you add the ability to skip or ignore specific findings? I know it could be possible to functionally ignore items by changing the passing score, but it would be useful to be able to specify which tests are run.

**Comment by 06kellyjac** [comment]
From #124 

Currently kubesec is exclusively a security risk analysis tool for Kubernetes.
If you or your team have a specific policy around ignoring x rule for y deployment then I'd advise you pipe the output into open-policy-agent/opa to apply that policy.

If there is a strong desire for ignoring rules then we can look at re-opening but it does get pretty messy when people only want to ignore rules for certain blocks within a multi block yaml file etc e.g. ignore privileged: true for deployment `foo` but dont for deployment `bar` leading to us suggesting a fully featured policy engine

**Comment by kevinlewis31** [comment]
I apologize, I failed to mention this was for use as a SaaS in a CI/CD pipeline, so I don't think your suggestion would work for our use case.

**Comment by 06kellyjac** [comment]
You can use opa within a pipeline to process the result of a hosted kubesec response. I might be missing something here

**Comment by 06kellyjac** [comment]
Since I've received no reply I'll be closing this
