### ISSUE TITLE
Default local schemas location doesn't exist 

### ISSUE THREAD

**Issue by fr33ky** [controlplaneio/kubesec#243]
Hi,

Trying to run `kubesec` as a `http` server (from docker image ` kubesec/kubesec:v2.11.4`), I noticed some network connection attempts to `https://kubernetesjsonschema.dev/master-standalone-strict/deployment-apps-v1.json`.
As a side note, I'm trying to get `kubesec` running in an air-gapped environment :).

Digging the code, I found that the default schema location is set (I guess) to `/schemas/kubernetes-json-schema/master/master-standalone`. If not correct it then falls back to  `kubeval` default URL:

https://github.com/controlplaneio/kubesec/blob/5e9096bc3293260d9d11cf06db5b0e235bea09b7/pkg/ruler/ruleset.go#L395

Unfortunately, this directory doesn't exist:
```
$ docker run --rm --entrypoint ls kubesec/kubesec:v2.11.4 /schemas
master-standalone-strict
```

We should either have this location or have the possibility, via flag or env variable, to set the schema location.

Many thanks for your help and such a tool!

**Comment by spiarh** [comment]
Hi @fr33ky, this has been recently updated and documented here: https://github.com/controlplaneio/kubesec#specify-custom-schema
