### ISSUE TITLE
Looking for Good first issue 

### ISSUE THREAD

**Issue by JOSHUAJEBARAJ** [controlplaneio/kubesec#251]
Hello Team, 
I am looking for  good first issue to start my contribution to project, I can help with  working on small features, writing small test cases and some part of the documentation , Let me know where can I get started 

Best Regards,
Joshua Jebaraj

**Comment by 06kellyjac** [comment]
I've tagged 2 issues with [good first issue](https://github.com/controlplaneio/kubesec/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3A%22good+first+issue%22)
