### ISSUE TITLE
VolumeClaimAccessModeReadWriteOnce VolumeClaimRequestsStorage issued when StatefulSet has no PVCs

### ISSUE THREAD

**Issue by mkmik** [controlplaneio/kubesec#281]
**Describe the bug**

kubesec advises a problem with `VolumeClaimAccessModeReadWriteOnce` and `VolumeClaimRequestsStorage`
when a `StatefulSet` has `volumeClaimTemplates`:

```
  {
    "id": "VolumeClaimAccessModeReadWriteOnce",
    "selector": ".spec .volumeClaimTemplates[] .spec .accessModes | index(\"ReadWriteOnce\")",
    "reason": "",
    "points": 1
  },
  {
    "id": "VolumeClaimRequestsStorage",
    "selector": ".spec .volumeClaimTemplates[] .spec .resources .requests .storage",
    "reason": "",
    "points": 1
  },
```

(It's perfectly legal for a StatefulSet to not have PVCs)

**To Reproduce**

call `kubesec scan` on a valid `StatefulSet` that has no `volumeClaimTemplates` (or `volumeClaimTemplates: []`)

**Expected behaviour**

No advising for `VolumeClaimAccessModeReadWriteOnce`  and `VolumeClaimRequestsStorage` if the stateful set doesn't have any `volumeClaimTemplates`

**Comment by olcuhu** [comment]
Fixed in https://github.com/controlplaneio/kubesec/pull/346
