### ISSUE TITLE
Deploy to Cloud Run

### ISSUE THREAD

**Issue by stefanprodan** [controlplaneio/kubesec#29]
- [x] create GCR repository
- [x] create Could Build triggers for git commits
- [x] create Cloud Run function for dev
- [x] deploy new revision to dev on git commit
- [x] create Cloud Run function with custom DNS for prod
- [ ] create Could Build triggers for git tags
- [ ] deploy new revision to prod on git tag

**Comment by 06kellyjac** [comment]
v2 is now in cloudrun
