### ISSUE TITLE
Support Apple Silicon M1 - "Error: does not offer installation for this platform"

### ISSUE THREAD

**Issue by nicolas-g** [controlplaneio/kubesec#383]
**Is your feature request related to a problem? Please describe.**

I cannot install kubesec on an Apple Silicon M1 machine.

```bash
kubectl krew install kubesec-scan
```

output
```text
0114 12:19:53.932299   25692 install.go:164] failed to install plugin "kubesec-scan": plugin "kubesec-scan" does not offer installation for this platform
failed to install some plugins: [kubesec-scan]: plugin "kubesec-scan" does not offer installation for this platform
```

**Describe the solution you'd like**

I would like it if the `kubectl krew install kubesec-scan` command could install the plugin successfully.

**Describe alternatives you've considered**

I can use docker run and run the container but this doesn't not offer the same convenience as I use all of my other Krew plugins directly from running `kubectl` commands.

**Additional context**
NA

**Comment by spiarh** [comment]
Thanks for the report! this repo is for `kubesec`, the repo for the plugin is: http://github.com/controlplaneio/kubectl-kubesec

It looks like there is already an issue for M1 support: https://github.com/controlplaneio/kubectl-kubesec/issues/73

Can you leave a comment here ? we'll have a look
