### ISSUE TITLE
The command, print-rules, does not work.

### ISSUE THREAD

**Issue by eengelking** [controlplaneio/kubesec#411]
**Version**
v2.12.0

**Describe the bug**
The documentation references `kubesec print-rules` as a means to output the rules used by Kubesec.  However, this command does not show in the `Available Commands` in Kubesec and does not work in general.

```bash
./kubesec print-rules
Error: unknown command "print-rules" for "kubesec"
Run 'kubesec --help' for usage.
Unknown command "print-rules" for "kubesec"
```

**To Reproduce**
Run `kubesec print-rules` as shown in the documentation.
https://github.com/controlplaneio/kubesec#print-the-scanning-rules-with-their-associated-scores

**Expected behaviour**
Print out the list of rules.

**Comment by spiarh** [comment]
This is currently only available on master, we need to cut a new release.

**Comment by spiarh** [comment]
I just cut a new release `v2.13.0`, please take a look [here.](https://github.com/controlplaneio/kubesec/releases)
