### ISSUE TITLE
Add "points" to JSON output?

### ISSUE THREAD

**Issue by rbren** [controlplaneio/kubesec#56]
For our purposes, we'd like to be able to see how many points each individual check is worth (and particularly if it's a positive or negative check).

Right now, you've got `json:"-"` for the Points field in `RuleRef` - any particular reason that field is being excluded from the response?

**Comment by sublimino** [comment]
No reason, just haven't got round to it yet!

I'd like to publish the scores on the website too.

What would you ideally see in the JSON response, would a "points" key with a positive or negative integer do?

**Comment by bobby-brennan** [comment]
Perfect!
