### ISSUE TITLE
Kubesec on docker hub is missing tags

### ISSUE THREAD

**Issue by 06kellyjac** [controlplaneio/kubesec#72]
The kubesec website says the following image is available when it currently isn't: `docker.io/kubesec/kubesec:v2`
<https://kubesec.io/#download-kubesec>

~Neither is `v1`~

Resolutions:

- [x] Add `v2` tag
- [ ] Add `latest` tag
- [ ] Make sure they wont disappear
- [ ] Build them when necessary

**Comment by sublimino** [comment]
Nice one @06kellyjac, I've pushed `gcr.io/ku
besec-v2/kubesec@sha256:a0292096fd5739e13ee9dd63630bbebca8b425818056bc690bace572ec63b7d1` as `docker.io/kubesec/kubesec:v2` as a manual fix, then this should go into the release process.

**Comment by olcuhu** [comment]
Resolved, v2 tag is available and up to date
