### ISSUE TITLE
Allow option to specify schema location

### ISSUE THREAD

**Issue by gvijayakumar-16** [controlplaneio/kubesec#95]
I am getting an error 
```resource.json: Failed initalizing schema https://kubernetesjsonschema.dev/master-standalone-strict/deployment-apps-I v1.json: tls: first record does not look like a TLS handshake```

Would it be possible to allow schema location as an option so that I can point it to a local location in our server rather than hitting the url. (Not all url's are allowed from our servers)

**Comment by 06kellyjac** [comment]
Changing the schema location would be a useful feature.

As for the issue you're having, I've tried various versions of kubesec but I've not managed to replicate your issue.

Can you let me know what version of kubesec you're using?

---

I've tried the following Docker images (highly unlikely to replicate the issue as it comes with schemas locally)
* `eb00a8f` (Most recent)
* `v2`
* `512c5e0` (from the `kubesec-test.yaml` example from the README)

I've also tried the binary (which will download the schemas when it runs)
* `v2.3.1`
* `v2.0.0`

`https://kubernetesjsonschema.dev/master-standalone-strict/deployment-apps-I v1.json` doesn't exist but `https://kubernetesjsonschema.dev/master-standalone-strict/deployment-apps-v1.json` does.
I've not managed to find a case where `deployment-apps-v1.json` has a `l ` added to it. This could be an issue with kubeval itself with a specific release of kubesec.

**Comment by gvijayakumar-16** [comment]
I am using the latest binary. 

The issue in my case is that the machines running kubesec does not have internet access. So it will not be able to access the specified url.

**Comment by 06kellyjac** [comment]
I see.
The flag for setting a different schema location (and some other changes) is almost done, need a couple more tweaks.

For now if you download a copy of the schemas to `/schema` (look at the `Dockerfile`) for some details it should read that. Or you can just use the docker images, it'll download the image the first time you run it but it has schemas bundled in it

**Comment by gvijayakumar-16** [comment]
Yes, I did find the work around by looking at the code. Just thought that would be good to have feature in case some one comes across the same scenario in future

**Comment by ipedrazas** [comment]
Maybe it would be good to add how `schemas` work into the docs

**Comment by AndreasMili** [comment]
https://github.com/controlplaneio/kubesec/pull/190

Feature is now in master!

**Comment by 06kellyjac** [comment]
I'll vendor a release later today

**Comment by desaintmartin** [comment]
I suppose this can be closed? ;)

**Comment by AndreasMili** [comment]
Yes, of course

**Comment by gvijayakumar-16** [comment]
Yes, thanks
