### ISSUE TITLE
documentation regarding mutiple yaml file scan is not clear

### ISSUE THREAD

**Issue by karthiksiva-github** [controlplaneio/kubesec#96]
Hi

Is there a way to run more than one yaml file checks using docker run command. If so, how to do it as it is not clear in the document

if possible provide commands for the same

**Comment by sublimino** [comment]
Kubesec only accepts a single file. You can combine multiple YAML files into one with the `---` separator and pass that to Kubesec, which will validate each document in the file separately.

You could also use `bash` to achieve this:

```bash
docker run -i kubesec/kubesec:d432be9 scan /dev/stdin < <(cat ./test/asset/score-1-prod-dump.yaml; echo '---'; cat ./test/asset/score-1-prod-dump.yaml)
```
